openshift/cluster-autoscaler-operator

Makefile
=> remove copyright notice

Dockerfile, Makefile
SSIA
Follow-up to PRs from other Cloud Team repositories.
/assign @bison @ingvagabund
=> fix fmt script invocation and remove k8s copyright notice

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
=> Add system-cluster-critical priority class to pods

pkg/operator/config.go, pkg/operator/operator.go
Adds leader-election on startup using a ConfigMap.
=> operator: Add optional leader-election on startup

pkg/controller/machineautoscaler/machineautoscaler_controller.go, pkg/controller/machineautoscaler/machinetarget.go, pkg/controller/machineautoscaler/machinetarget_test.go
This adds an annotation marking targets as owned by the
MachineAutoscaler resources that reference them.  It also watches all
supported target types for changes and queues reconciliation requests
for the owning MachineAutoscaler resource.  If multiple
MachineAutoscaler resources reference the same target, the first wins
and reconciliation will fail for the others.
=> Mark targets as owned by MachineAutoscaler resources

pkg/controller/machineautoscaler/machineautoscaler_controller.go
If not-found errors returned by the update call in the finalizer are
not ignored, then deleting a MachineAutoscaler that targets a deleted
or otherwise missing MachineSet will hang forever.  This ignores
not-found errors when finalizing after deletion or last-target change.
=> Ignore not-found errors when finalizing resources

install/0000_50_cluster-autoscaler-operator_04_deployment.yaml, kustomization.yaml
=> Use kustomize to deploy CA operator in k8s

Makefile, cluster-autoscaler-operator-patch.yaml, kustomization.yaml, test/e2e/main.go, test/e2e/operator_expectations.go, test/resources/cluster.yaml, test/resources/machine-set.yaml
We need to be able to iterate quickly and test scenarios without
consuming too much resouces.
=> Prepare test/e2e to be run over pure k8s (over kubemark based machine API)

pkg/operator/status.go, test/e2e/main.go, test/e2e/operator_expectations.go
- Introduce expect for cluster operator status 
- Fix dependency cluster operator status name, machine-api
- Better logging
=> Add expect for cluster operator status

pkg/controller/clusterautoscaler/clusterautoscaler.go, pkg/controller/clusterautoscaler/clusterautoscaler_controller.go, pkg/operator/config.go, pkg/operator/operator.go
Adds configurable verbosity for autoscaler logging.
=> Add configuration option for autoscaler logging verbosity

test/resources/machine-set.yaml
=> Rename labels from sigs.k8s.io to machine.openshift.io

pkg/operator/status.go, pkg/operator/status_test.go
Fixes: https://jira.coreos.com/browse/CLOUD-392
Depends-on: https://github.com/openshift/cluster-autoscaler-operator/pull/63
=> Add status=progressing for version difference

pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Add unit tests for AvailableAndUpdated() to ensure
cao status=progressing/available logic is correct.
=> ca_controller: implement unit tests

pkg/controller/clusterautoscaler/clusterautoscaler_test.go
Validate logic of Reconcile with unit tests.
=> ca_controller: add Reconcile unit tests

pkg/controller/machineautoscaler/machineautoscaler_controller.go, pkg/controller/machineautoscaler/machineautoscaler_controller_test.go, pkg/controller/machineautoscaler/machinetarget.go, pkg/controller/machineautoscaler/machinetarget_test.go, pkg/operator/operator.go
Fixes an issue with inadvertently modifying the SupportedGVKs in-place.
=> Fix bug with filtering supported MachineAutoscaler GVKs

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go, pkg/controller/clusterautoscaler/clusterautoscaler_test.go, pkg/controller/machineautoscaler/machineautoscaler_controller.go, pkg/controller/machineautoscaler/machineautoscaler_controller_test.go, pkg/controller/machineautoscaler/machinetarget.go, pkg/controller/machineautoscaler/machinetarget_test.go
Records events alongside logging for error and success conditions in the reconcilers.
=> Record events in all controllers

Gopkg.lock, Gopkg.toml, cmd/manager/main.go, pkg/controller/clusterautoscaler/clusterautoscaler_controller.go, pkg/controller/machineautoscaler/machineautoscaler_controller.go, pkg/operator/config.go, pkg/operator/status.go, test/e2e/operator_expectations.go
Moving from glog to klog to align with related projects.
=> Move from glog to klog

README.md
Adds info to the README on validating webhooks.
=> README: Add info on webhook infrastructure

pkg/operator/operator.go, pkg/operator/operator_test.go
Add clusterAutoscalers and machineAutoscalers to  RelatedObjects
=> Add clusterAutoscalers and machineAutoscalers to  RelatedObjects

install/07_deployment.yaml
For more detailed description see https://github.com/openshift/origin/issues/24247#issuecomment-560412327
=> Add resource request to container

install/03_rbac.yaml
1.17 introduce leader election mechanism to use lease objects https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.17.0
See https://github.com/kubernetes/autoscaler/commit/5dffd75f5bc9b8878d22f9cea07539e6668a98b2
=> Add perms for leases.coordination.k8s.io

OWNERS
Allow myself, @elmiko and @alexander-demichev to approve PRs in the future
=> Update owners to add new team members

pkg/operator/operator.go, pkg/operator/operator_test.go
Fix API group on related resources
=> Bug 1817860: Fix API group on related resources

hack/gen-crd.sh, install/01_clusterautoscaler.crd.yaml, install/02_machineautoscaler.crd.yaml
Bump apiextensions to v1 on CRD generation
=> Bug 1829263: Bump apiextensions

install/00_namespace.yaml, install/01_clusterautoscaler.crd.yaml, install/02_machineautoscaler.crd.yaml, install/03_rbac.yaml, install/04_service.yaml, install/05_kube_rbac_proxy.yaml, install/06_servicemonitor.yaml, install/07_deployment.yaml, install/08_clusteroperator.yaml, install/09_alertrules.yaml, install/10_cluster_reader_rbac.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

Dockerfile, Makefile, go.mod, hack/go-fmt.sh, hack/go-lint.sh, hack/go-vet.sh, hack/goimports.sh, vendor/modules.txt
Unblocks https://github.com/openshift/release/pull/13785
=> [OCPCLOUD-977] Bump scripts to Go 1.15

install/03_rbac.yaml, install/05_kube_rbac_proxy.yaml, install/10_cluster_reader_rbac.yaml
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.
=> Bug 1948706: Add IBM Cloud managed annotations to CVO manifests

Makefile, README.md, hack/go-fmt.sh, hack/go-lint.sh, hack/go-mod.sh, hack/go-vet.sh, hack/goimports.sh, hack/imagebuilder.sh, hack/owner_reset.sh
Update make targets to be able to run in container with podman and docker, as well as run without container.
=> Update makefile to support podman

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
Bump prometheus/client_golang to the newest release.
=> Bug 2067803: Bump prometheus/client_golang

hack/gen-crd.sh, install/01_clusterautoscaler.crd.yaml, install/02_machineautoscaler.crd.yaml, install/05_kube_rbac_proxy.yaml, install/06_servicemonitor.yaml, install/07_deployment.yaml, install/08_clusteroperator.yaml, install/10_cluster_reader_rbac.yaml, install/99_tombstones.yaml
Add capability annotation to manifests to make operator optional
=> CNF-5642 make operator optional

Makefile, pkg/operator/operator.go
Manual backport of #281 and #282.
=> [release-4.13] OCPBUGS-17056: Address long acquire times during update

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-23706: Add Snyk file to exclude vendor directory on scan

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-25749: Add Snyk file to exclude vendor directory on scan

OWNERS
Adds autoscale-team members as reviewers.
=> NO-JIRA: Add autoscale members to OWNERS file
