openshift/cluster-autoscaler-operator

cmd/manager/main.go
examples/clusterautoscaler.yaml
install/0000_50_cluster-autoscaler-operator_01_clusterautoscaler.crd.yaml
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/controller.go
pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/operator/config.go

This makes the ClusterAutoscaler resource a singleton. The CRD becomes cluster-scoped and the operator only watches a single instance. The name of the instance to watch is configurable at runtime.
It also allows for overriding the cluster-autoscaler image via an environment variable.

Make ClusterAutoscaler resource a singleton

---

Dockerfile
Makefile
cmd/manager/main.go
pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go
pkg/controller/machineautoscaler/machinetarget.go
pkg/controller/machineautoscaler/machinetarget_test.go
pkg/operator/config_test.go
pkg/util/util.go
pkg/util/util_test.go
version/version.go

This adds the start of a unit-test suite. It also sets version information at build time, and adds a type to help with generating cluster-autoscaler arguments.

Add initial unit-test suite

---

examples/clusterautoscaler.yaml
examples/machineautoscaler.yaml
install/0000_50_cluster-autoscaler-operator_00_namespace.yaml
install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/operator/config.go

We decided on deploying this to the `openshift-cluster-api` namespace along with other components for now. This updates the namespace and uses the actual OpenShift image for the autoscaler.

Deploy to correct namespace

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machinetarget.go
pkg/controller/machineautoscaler/machinetarget_test.go

The cluster-autoscaler has moved to using annotations instead of
labels for the min and max sizes of a group.  This updates
MachineTarget resources to set the limits as annotations.
https://github.com/openshift/kubernetes-autoscaler/pull/11
Note: This doesn't perform any kind of migration from labels to annotations. I don't think anyone is using this yet, or is even really using the cluster-api provider in the autoscaler, so it's probably not necessary. We could do it if we wanted though.

Use annotations instead of labels for min and max

---

Dockerfile
Dockerfile.rhel7
Makefile
install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
install/image-references
test/e2e/main.go
test/e2e/operator_expectations.go

This adds the first step towards e2e tests based on the recent work in the machine-api-operator. It also adds a deployment manifest and related bits to enable the operator in the CVO.

Add initial e2e test suite

---

Makefile
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

Adds the toleration and node selector to the autoscaler pod to schedule it on master nodes.
Fixes #18.

Run autoscaler pods on master nodes

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go

The use of the cluster-api is moving away from MachineSets directly to
higher level MachineDeployment resources.  This adds MachineDeployment
resources as an additional supported target type for MachineAutoscaler
objects.  MachineSets may be removed at some point.

Add MachineDeployment as a supported target

---

install/0000_50_cluster-autoscaler-operator_02_machineautoscaler.crd.yaml

Pretty print in CLI as follows:
```sh
oc get machineautoscalers --all-namespaces
NAMESPACE               NAME                         REF KIND     REF NAME                        MIN       MAX       AGE
openshift-cluster-api   autoscale-us-east-2a-96b87   MachineSet   commonsdemo-worker-us-east-2a   1         12        12m
```

Printer columns for machine autoscaler

---

install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
install/image-references

This pulls the autoscaler image into the release and uses that for deployments.

Use correct cluster-autoscaler image reference

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

The autoscaler pod should be limited to Linux nodes.

Only run the autoscaler pod on Linux nodes

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machineautoscaler_controller_test.go

This adds validation to MachineAutoscaler target references.
Previously, if for example a reference had no name set, the dynamic
client would return a list and cause a panic.  This prevents fetching
invalid or unsupported target references.

Properly validate MachineAutoscaler target references

---

install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
install/0000_50_cluster-autoscaler-operator_04_deployment.yaml

The role and binding were present in the CVO manifests, but the
actual ServiceAccount was missing.  This adds it, and configures the
operator deployment to use it.

Use the correct ServiceAccount for the operator

---

test/e2e/main.go

This reverts commit a9fe0c752a179de93b199f2adfcd139d500987e6.
***Commented out test allowed PR #35 getting merged.***
Waiting for https://github.com/openshift/kubernetes-autoscaler/pull/29 to get merged.

Revert "Disabling ExpectClusterAutoscalerAvailable e2e test temporarily."

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go

This checks for errors resulting from unregistered types when
initializing the MachineAutoscaler reconciler and removes them from
the list of supported target types.

Remove unregistered types from supported target types

---

pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go
pkg/controller/clusterautoscaler/clusterautoscaler.go

It takes 10 minutes before a cluster is scalled down (default value of --scale-down-unneeded-time).
Allowing to override the option allows to decrease the time spend waiting
on scale down operation in both testing and development environment.
Also can help customer to scale down sooner.

Allow to configure --scale-down-unneeded-time

---

README.md
examples/machineautoscaler.yaml
install/0000_50_cluster-autoscaler-operator_00_namespace.yaml
install/0000_50_cluster-autoscaler-operator_03_rbac.yaml
install/0000_50_cluster-autoscaler-operator_04_deployment.yaml
pkg/operator/config.go
test/e2e/main.go

Change namespace to openshift-machine-api
Needs https://github.com/openshift/machine-api-operator/pull/202 and counterpart installer PR https://github.com/openshift/installer/pull/1215

Change namespace to openshift-machine-api

---

install/0000_50_cluster-autoscaler-operator_04_deployment.yaml

This was reported in Bugzilla. Second-level-operators are expected to set resource requests, but explicitly should *not* set limits.

Remove resource limits in operator deployment

---

cluster-autoscaler-operator-patch.yaml

Currently specified image docker.io/openshift/origin-cluster-autoscaler-operator:v4.0 is not available.
Using the one in quay instead.

Override default CAO image

---

install/0000_50_cluster-autoscaler-operator_04_deployment.yaml

As of now, cluster-autoscaler-operator doesn't have `system-node-critical` priorityClass names, the pods created for this deployment may get evicted by scheduler, if this priorityClass is not available. The rationale behind adding `system-node-critical` is we have nodeSelector to ensure that we are running on master nodes.

 Add cluster-critical priority to autoscaler-operator

---

pkg/operator/status.go
pkg/operator/status_test.go

This commit refactors business logic of Report() to
it's own function, ApplyStatus().  This assists
in unit testing.
This test also implements behavior validation for
critical status reporting logic.

Operator: move report logic to ApplyStatus function

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

This commit adds some extra logging to ensure we capture
information during availability checks.

Add additional logging

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/util/util.go
pkg/util/util_test.go

This refactors the StatusReporter to satisfy the Runnable interface
and adds it to the manager when creating a new Operator instance.
This prevents it from starting before clients are set up, and from
reporting status before leader-election has succeeded.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1689146

Make StatusReporter a Runnable added to the manager

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go
pkg/operator/status_test.go
test/helpers/helpers.go

Because ClusterAutoscaler objects are cluster scoped, events related
to these objects were being recorded in the default namesapce.  This
causes the events to be recorded in the namespace that the deployment
is created in.
This also adds some unit tests for the `UpdateAnnotations` method.

Record ClusterAutoscaler events in correct namespace

---

pkg/controller/clusterautoscaler/clusterautoscaler_test.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/util/util.go
pkg/util/util_test.go
test/helpers/helpers.go

The LastTransitionTime of the ClusterOperator object's Progressing
status condition is always expected be updated after an upgrade --
even if there are no operands deployed.  In that case, Progressing
never changes status, but its timestamp must still be updated.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1695209

Always reset LastTransitionTime on Progressing condition

---

examples/clusterautoscaler.yaml

Adds some text to explain what the option does and what the default
timeout value will be if omitted.

examples/clusterautoscaler: add commentary on sample values

---

Makefile

This is an attempt to remove the control characters from the CI logs.
If you look at the end of https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/277/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/778/build-log.txt you'll see lots of unprintable characters. The goal here is to remove these from CI logs to make them easier to consume and parse.
If you want colour you can always post process using ccze(1)[1]
[1] - https://github.com/cornet/ccze

Makefile: add -ginkgo.noColor=true for e2e invocations

---

Gopkg.lock
Gopkg.toml

The cluster-api-actuator-pkg has the fixes for the change to v1beta1 and v1 versions now. Switching back to the master branch. The code is the same, so no changes needed in `vendor` -- this just updates the `Gopkg.*` files.

Switch back to master branch of cluster-api-actuator-pkg

---

pkg/operator/status.go

status=Failing has been removed on CVO.  Removing
support.

Remove status=Failing support

---

cmd/manager/main.go
install/00_namespace.yaml
install/03_rbac.yaml
install/04_service.yaml
install/06_deployment.yaml
install/09_servicemonitor.yaml
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/operator/config.go
pkg/operator/config_test.go
pkg/operator/operator.go

This enables monitoring integration for cao.
- Controller runtime metrics are exposed for machine_autoscaler_controller and cluster_autoscaler_controller
- This enables any farther metric to be scraped by prometheus for either these controllers or any managed component i.e machine-provider/cluster-autoscaler

Monitoring integration

---

README.md
examples/clusterautoscaler.yaml
install/01_clusterautoscaler.crd.yaml
pkg/apis/autoscaling/v1/clusterautoscaler_types.go
pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
pkg/apis/autoscaling/v1/zz_generated.openapi.go
pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

Add support for enabling the --balance-similar-node-groups
cluster-autoscaler option. It defaults to disabled but can be enabled
as follows:
```yaml
apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
name: "default"
spec:
balanceSimilarNodeGroups: true
```

Enable autoscaler --balance-similar-node-groups option

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go
pkg/controller/clusterautoscaler/validator.go
pkg/controller/clusterautoscaler/validator_test.go
pkg/operator/operator.go
pkg/operator/webhookconfig.go

This adds a validator type for ClusterAutoscaler resources.  It handles validation both inside the reconciliation loop, where it returns early and records an event on failure, and for the validating webhook.
Here's an example of the reporting users now get earlier in the flow of deploying the cluster-autoscaler -- here the maximum number of cores was lower than the minimum and one of the durations in the scale down configuration was invalid:
```console
$ kubectl apply -f clusterautoscaler.yaml 
Error from server ([ResourceLimits.Cores: Max must be greater than or equal to Min, ScaleDown.DelayAfterAdd: time: invalid duration bad-duration]): error when creating "clusterautoscaler.yaml": admission webhook "clusterautoscalers.autoscaling.openshift.io" denied the request: …
```

Add validator for ClusterAutoscaler resources

---

pkg/controller/clusterautoscaler/validator.go
pkg/controller/clusterautoscaler/validator_test.go
pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
pkg/controller/machineautoscaler/validator.go
pkg/controller/machineautoscaler/validator_test.go
pkg/operator/operator.go
pkg/operator/webhookconfig.go

This adds a validator type for MachineAutoscaler resources. It handles
validation both inside the reconciliation loop, where it returns early
and records an event on failure, and for the validating webhook.

Add validator for MachineAutoscaler resources

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machineautoscaler_controller_test.go
pkg/controller/machineautoscaler/validator_test.go

This moves the handling of changes to MachineAutoscaler targets to
early in the reconciliation process -- just after handling of
deletion.  Otherwise, it's possible for the previous target to never
have its autoscaling configuration removed if there's some problem
fetching the new target.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1733471

Bug 1733471: Fix MachineAutoscaler target updates

---

pkg/operator/status.go
pkg/operator/status_test.go

This sets the Upgradeable condition on the status of the operator's
ClusterOperator resource.  This always reports as true for now as
there is no condition which should prevent the operator from
upgrading.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1727015

Bug 1727015: Set Upgradeable condition on ClusterOperator status

---

README.md
examples/clusterautoscaler.yaml
install/01_clusterautoscaler.crd.yaml
pkg/apis/autoscaling/v1/clusterautoscaler_types.go
pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

These options are being used in 3.11. This PR enables these options and makes it possible to be able to set these at the cluster autoscaler operator.
https://jira.coreos.com/browse/CLOUD-603

Enable ignore-daemonsets-utilization and skp-nodes-with-local-storage

---

install/03_rbac.yaml

This requirement was introduced by https://github.com/kubernetes/autoscaler/pull/2305 and fixed for e.g aws here https://github.com/kubernetes/autoscaler/pull/2404

Add csinodes to autoscaler ClusterRole

---

install/04_service.yaml
install/06_servicemonitor.yaml
install/07_deployment.yaml
install/08_clusteroperator.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

pkg/operator/status.go

Previously errors applying updates to the operator's ClusterOperator
status were silently ignored.  This is mostly a problem when there's
an error reporting the Available status, because there is no immediate
retry in that case, which leaves the CVO unaware of the operator's
success.  This changes the reporter to always log errors applying the
updates, and to retry in the case the case of an error applying the
Available status.

Bug 1779640: Don't suppress errors when reporting operator status

---

pkg/operator/status.go

Previously errors applying updates to the operator's ClusterOperator
status were silently ignored.  This is mostly a problem when there's
an error reporting the Available status, because there is no immediate
retry in that case, which leaves the CVO unaware of the operator's
success.  This changes the reporter to always log errors applying the
updates, and to retry in the case the case of an error applying the
Available status.
cherry-picks https://github.com/openshift/cluster-autoscaler-operator/pull/124

bug 1779741: Don't suppress errors when reporting operator status

---

pkg/operator/status.go

Previously errors applying updates to the operator's ClusterOperator
status were silently ignored.  This is mostly a problem when there's
an error reporting the Available status, because there is no immediate
retry in that case, which leaves the CVO unaware of the operator's
success.  This changes the reporter to always log errors applying the
updates, and to retry in the case the case of an error applying the
Available status.
Cherry-pick of:
https://github.com/openshift/cluster-autoscaler-operator/pull/124
https://github.com/openshift/cluster-autoscaler-operator/pull/125

Bug 1779743: Don't suppress errors when reporting operator status

---

pkg/operator/status.go

Previously errors applying updates to the operator's ClusterOperator
status were silently ignored.  This is mostly a problem when there's
an error reporting the Available status, because there is no immediate
retry in that case, which leaves the CVO unaware of the operator's
success.  This changes the reporter to always log errors applying the
updates, and to retry in the case the case of an error applying the
Available status.
Cherry-pick of:
https://github.com/openshift/cluster-autoscaler-operator/pull/124
https://github.com/openshift/cluster-autoscaler-operator/pull/125
https://github.com/openshift/cluster-autoscaler-operator/pull/126

Bug 1779745: Don't suppress errors when reporting operator status

---

install/00_namespace.yaml
install/07_deployment.yaml

cao should follow normal admission control rules for a cluster.
Needs https://github.com/openshift/machine-api-operator/pull/502

BUG 1806438: Drop run-level

---

hack/gen-crd.sh
install/01_clusterautoscaler.crd.yaml
install/02_machineautoscaler.crd.yaml
install/09_alertrules.yaml

Remove prometheus rule and autoscaler CRD that should not be present in a hosted
control plane deployment.

Bug 1809325: ROKS - remove additional autoscaler manifests

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/operator/config.go

Since we merged the clusterapi provider upstream we are now consuming that directly https://github.com/openshift/kubernetes-autoscaler/pull/139
This is to minimise the commits we need to carry on top by using the upstream flag/env variables.

Set clusterapi flag and env variable for group

---

pkg/controller/clusterautoscaler/monitoring.go

cluster_autoscaler_nodes_count records the total number of "Autoscaler nodes" (i.e expected candidates to join the cluster), labeled by node state. Possible states are ready, unready, notStarted
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/metrics.md#cluster-state
The alert triggers if there's a least one node labeled different than "ready" in the "nodes_count" for more than 20min https://github.com/openshift/cluster-autoscaler-operator/blob/8e6f95038c9eee84ef7e305e2e1f4960c918b30d/pkg/controller/clusterautoscaler/monitoring.go#L184
This alert might be triggering for periods where constant increase/decrease of workload happens resulting in constant scale in/out of the cluster.
An "Autoscaler nodes" is always backed by a machine resource. Since we have …

BUG 1813069: Drop ClusterAutoscalerNodesNotReady alert

---

install/10_cluster_reader_rbac.yaml

Added cluster-reader permissions to `cluster-autoscaler` cluster-role

Bug 1796412: cluster-reader is unable to view machine resources

---

pkg/operator/status.go

We've used `ReasonEmpty` since 72cd9c4d76 (#23).  But if we feel like we have a message we want to set to help humans understand the condition, we should be setting a reason string for machines too.  AsExpected follows [the library-go precedent][1].
[1]: https://github.com/openshift/library-go/blob/94c59dec54be25c8527e51e8c0a885712aeb01b5/pkg/operator/status/condition.go#L67

pkg/operator/status: Change ReasonEmpty to ReasonAsExpected

---

Makefile
hack/verify-actuator-pkg.sh

CI stopped using it almost 1 year ago since
https://github.com/openshift/release/pull/4060/commits/cd154392fad5bb511

Remove verify-actuator-pkg.sh

---

docs/dev/metrics.md

This change adds a document to describe the metrics available from this
operator.
/kind documentation

add metrics.md to document exposed metrics

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

Currently we did not place boolean arguments if they were not true,
which didn't allow to set an option to false.
While some arguments might be true by default (SkipNodesWithLocalStorage)
others (balanceSimilarNodeGroups) are false by default. So let's
set the value explicitely for the few boolean values.

Bug 1854907: Fix #155 - ensure full boolean arguments

---

install/01_clusterautoscaler.crd.yaml
pkg/apis/autoscaling/v1/clusterautoscaler_types.go
pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

In baremetal environments it can easily take longer than the CA
default of 15mins for the node to become active after a scale-out
action.
The CA supports --max-node-provision-time[1] so adding support to
enable configuration of that value should allow tuning of the
time such that it's more suited to baremetal.
[1] https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca

Bug 1861642: Add maxNodeProvisionTime for baremetal

---

Dockerfile.rhel
Dockerfile.rhel7

This creates a Dockerfile.rhel file according to convention and symlink Dockerfile.rhel7 to the new one to satisfy tooling consumers until we switch them

Bug 1872080: Create Dockerfile.rhel file

---

Dockerfile.rhel7

This change removes the now deprecated Dockerfile.rhel7 in favor of the
new Dockerfile.rhel file.

Bug 1875036: remove Dockerfile.rhel7

---

go.mod
go.sum
vendor/github.com/evanphx/json-patch/.travis.yml
vendor/github.com/evanphx/json-patch/LICENSE
vendor/github.com/evanphx/json-patch/README.md
vendor/github.com/evanphx/json-patch/merge.go
vendor/github.com/evanphx/json-patch/patch.go
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
vendor/k8s.io/apimachinery/pkg/util/json/json.go
vendor/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
vendor/k8s.io/client-go/rest/request.go
vendor/k8s.io/client-go/tools/cache/controller.go
vendor/k8s.io/client-go/tools/cache/reflector.go
vendor/k8s.io/client-go/tools/clientcmd/client_config.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
vendor/modules.txt

This is to include a fix in the reflector for not recovering from "Too large resource version".
See [attached bug](https://bugzilla.redhat.com/show_bug.cgi?id=1880320) which contains details of the issue.

Bug 1880320: Bump K8s dependencies to v0.18.9

---

OWNERS

This change adds the bugzilla component name to the OWNERS file to
comply with the prodsec requirements for OpenShift builds through ART.

add bugzilla component to OWNERS

---

hack/gen-crd.sh
install/01_clusterautoscaler.crd.yaml
install/02_machineautoscaler.crd.yaml
pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go

This ensures that CRD generation is up to date and that newer links are included in descriptions for core typemeta/metadata fields

Bug 1876469: Update generated CRDs

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

Currently we did not place boolean arguments if they were not true,
which didn't allow to set an option to false.
While some arguments might be true by default (SkipNodesWithLocalStorage)
others (balanceSimilarNodeGroups) are false by default. So let's
set the value explicitely for the few boolean values.

Bug 1879162: ensure full boolean arguments

---

Makefile
hack/gen-crd.sh
hack/verify-diff.sh

Allowing automatic make generate checks in CI. It allows to keep track of API changes, client-generated code updates on each PR.
This PR is dependent on openshift/release#13400 to enable the functionality in CI.

[OCPCLOUD-809] Add verify-diff check in generate task and enable in CI

---

install/03_rbac.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior
---
It was one of the first repos I changed and I missed the fact that some files can contain multiples manifests.

add current profile annotations to CVO manifests

---

install/03_rbac.yaml

This change updates the ClusterRole for the cluster-autoscaler to
include the resource `machineset/scale` for list/get/update/watch
verbs. The new resource is being added to support the change in the
autoscaler to remove structure types[0].
[0] https://github.com/openshift/kubernetes-autoscaler/pull/177

add machineset/scale resource to the cluster-autoscaler role

---

install/07_deployment.yaml

The Kube RBAC Proxy containers are logging excessively. Having log level 10 includes logging bearer tokens and full http request/responses. This is insecure, more logging than we need, and has an impact on aggregated logging. Reduce to 3 to be inline with other components.

Bug 1907380: Reduce verbosity of kube-rbac-proxy logging

---

hack/gen-crd.sh
install/01_clusterautoscaler.crd.yaml
install/02_machineautoscaler.crd.yaml
install/03_rbac.yaml
install/04_service.yaml
install/05_kube_rbac_proxy.yaml
install/06_servicemonitor.yaml
install/07_deployment.yaml
install/08_clusteroperator.yaml
install/09_alertrules.yaml
install/10_cluster_reader_rbac.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-autoscaler-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

install/07_deployment.yaml

The default ciphers are not secure and are susceptible to a number of different known vulnerabilities. This collection of ciphers should be more secure and have no known vulnerabilities present.
Suites inspired by the [cluster-monitoring-operator](https://github.com/openshift/cluster-monitoring-operator/blob/f98cd6d7d1dc50fe881c6aa29d772a581451afd1/manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml#L54).

Bug 1923823: Improve TLS configuration for Kube RBAC Proxy

---

pkg/operator/webhookconfig.go

Move webhook to v1 because v1beta1 will be removed in 4.9.

Bug 1947785: Move webhook to v1

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

We are missing requests on autoscaler pods which are deployed after `ClusterAutoscaler` resource is created in the cluster.

Bug 1938467: The default cluster-autoscaler should get default cpu and memory requests if user omits them

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

These seem to be the wrong way around and I think this is now causing CI failures

Bug 1938467: Fix cluster autoscaler pod requests

---

install/07_deployment.yaml
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/util/util.go

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

install/03_rbac.yaml

rbac v1beta1 support was [removed](https://github.com/openshift/cluster-version-operator/pull/565) from CVO, so autoscaler should use v1 RBAC

Bug 1960554: manifests: use v1 for RBAC

---

pkg/operator/webhookconfig.go

Move all webhooks to v1 because v1beta1 will be removed in 4.9.

Bug 1947785: Move all webhooks to v1

---

install/03_rbac.yaml

The autoscaler will need to watch, list, and get these for normal
operation.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1973567

Bug 1973567: add csidrivers to the cluster-autoscaler cluster role

---

install/08_clusteroperator.yaml

This change adds the autoscaler specific resources to the
ClusterOperator manifest.

[OCPCLOUD-1174] Add related objects to ClusterOperator

---

install/03_rbac.yaml

The autoscaler will need to watch, list, and get these for nomral
operation.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1973567

Bug 1973567: add csistoragecapacities to cluster-autoscaler cluster role

---

install/99_tombstones.yaml

CVO has added the ability to remove objects created in previous releases
of OpenShift. This change adds a manifest to remove old objects which
are no longer used by the cluster-autoscaler-operator.
ref: https://issues.redhat.com/browse/OTA-395

[OCPCLOUD-1153] add a tombstones manifest to the install directory

---

docs/user/alerts.md
pkg/controller/clusterautoscaler/monitoring.go

This change adds the alerts for when the cluster autoscaler is unable to
scale out due to reaching cpu or memory limits. It also updates the
alert documents.
ref: https://issues.redhat.com/browse/OCPCLOUD-923

[OCPCLOUD-923] add alerts for memory and cpu core limits

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

This is breaking our tests which use foreground deletion. The CAO fights the GC to delete and recreate the deployment, ensuring that the CA CR never goes away.
I have manually verified that this fixes the broken cluster autoscaler tests we are currently seeing in CI.

Bug 1986090: Do not recreate CA deployment when CA CR is being deleted

---

install/99_tombstones.yaml

This change adds the annotation
`include.release.openshift.io/self-managed-high-availability: "true"`
to the tombstones. This is needed to ensure that the CVO will process
them.

Bug 1988032: add cvo ha annotation to tombstones

---

install/03_rbac.yaml

The autoscaler will need to watch, list, and get these for normal
operation.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1995595

 [release-4.8] Bug 1995595: add csidrivers and csistoragecapacities to autoscaler cluster role

---

pkg/controller/clusterautoscaler/monitoring.go

This alert is informational for the cluster operator, and doesn't describe an actual problematic condition that requires human action.
Per the documentation:
> In many cases this alert is normal and expected depending on the configuration of the autoscaler.
As such, lowering the severity of this to "info".

Bug 2025230: Change ClusterAutoscalerUnschedulablePods severity to info

---

pkg/controller/clusterautoscaler/monitoring.go

This change converts the `message` field to `summary` and adds a
`description` for each alert. This is being changed to bring the CAO
alerts into alignment with the alerting style guide.
ref:
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide

Bug 2026178: update alerts to match style guidance

---

go.mod
go.sum
install/03_rbac.yaml
vendor/modules.txt

updated to include missed rbac permission for infrastructure resource
updated library-go to latest for fix in pr https://github.com/openshift/library-go/pull/1273
Signed-off-by: ehila <ehila@redhat.com>

Bug 2034484: fix: missed rbac and latest library-go

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

This change adds the `CAPI_VERSION` environment variable to the
container spec for the cluster autoscaler, set to `v1beta1`. It is being
added to better scope the resources that the autoscaler watches, and to
mitigate unwanted `v1` objects from being selected.

add capi version to autoscaler deployment

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

This change is being added to bring the cluster autoscaler deployment in
line with the OpenShift conventions[0] for leader election. It also adds
test for the default flags to help prevent regressions.
[0] https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md

Bug 2063194: add leader election flags to autoscaler deployment

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

This change is being added to bring the cluster autoscaler deployment in
line with the OpenShift conventions[0] for leader election. It also adds
test for the default flags to help prevent regressions.
[0] https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md

Bug 2070277: add leader election flags to autoscaler deployment

---

docs/user/alerts.md
pkg/controller/clusterautoscaler/monitoring.go

this change updates the resource limit alerts to use the new metric introduced in https://github.com/kubernetes/autoscaler/pull/5059.

Bug 1997396: update alerts for resource limits

---

pkg/controller/clusterautoscaler/monitoring.go

the new rules for the resource limits failed to include the time unit for the range vector, this change fixes that.

Bug 1997396: fix an error with autoscaler alert rules

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

this change makes the autoscaler deploy with the duplicated events flag (`--record-duplicated-events`). this change is being added because the upstream have added this flag in the 1.25 release, which allows us to drop carried functionality from the autoscaler.

OCPCLOUD-1677: add flag for duplicated events

---

install/06_servicemonitor.yaml

Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

Add client certificate and key to service monitor

---

install/07_deployment.yaml

This PR sets a default container for the cluster autoscaler operator.

[OCPCLOUD-1708]: Set default container for operator

---

pkg/controller/clusterautoscaler/clusterautoscaler.go
pkg/controller/clusterautoscaler/clusterautoscaler_controller.go
pkg/controller/clusterautoscaler/clusterautoscaler_test.go

This PR adds the ability for us to determine what provider platform are we using. With that knowledge, we can always append ignore zone labels for related platforms.
cc @elmiko

[OCPCLOUD-1702]: Update CAO to ignore platform related zone labels

---

pkg/operator/operator.go

This PR is an addition this PR #260, that added ignore labels for specific cloud providers. QE came across an error, where the new `configv1.Infrastructure` type was not registered to the schemes. This PR solves that issue.

Register configv1 types to schemes

---

install/03_rbac.yaml

This PR is still associated to #260. We are encountering an error that QE posted in the JIRA card here: https://issues.redhat.com/browse/OCPCLOUD-1702
We were not able to list the object `infrastructures.config.openshift.io` as we should, since this new object was introduced in the aforementioned PR. We try to fix this issue by adding `list` verb to the `apiGroups` field for `config`.

Allow infrastructures.config.openshift.io to be listed

---

install/03_rbac.yaml

Fix for this story: https://issues.redhat.com/browse/OCPCLOUD-1702. QE was still running into some issue with the `Infrastructures` resource not being able to be listed in API group `config.openshift.io` at the cluster scope.

Add infrastructures resource to config.openshift.io

---

README.md
pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machinetarget.go
pkg/controller/machineautoscaler/machinetarget_test.go

this change is reverting the addition of the GPU label to MachineSet objects as part of the CAO's GPU identification. It is being reverted for a few reasons: the label is added to the wrong place on the MachineSet, the label does not have the correct value, the label is not being processed by the cluster autoscaler, and we have decided to not have this bug fix automatically change values for the user.
This change does not have an impact on user experience as this value was never being processed by the cluster autoscaler and should not pose a risk to any user who is migrating older MachineSets as the label is effectively a no-op.
ref: https://github.com/openshift/cluster-autoscaler-operator/pull/223
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1943194

revert GPU label changes from pr 223

---

pkg/controller/clusterautoscaler/clusterautoscaler.go

This change ammends the balancing label ignore logic to include the Nutanix specific labels which should be ignored.

OCPBUGS-14356: add nutanix labels that should be ignored

---

pkg/operator/operator.go

The upgrade of cluster-autoscaler-operator the  was delayed significantly by lease acquire times, so we add flag `LeaderElectionReleaseOnCancel: true` to the `manager.Options` struct to make sure that when the manager gets shutdown, the leader steps down voluntarily. 
In order to set this condition, we need to make sure that the binary is stopped immediately when the manager is stopped, which in this case should be ok (discussed with @elmiko). 
The outcome for this change is that leader transitions are much quicker as the new leader doesn't have to wait for `LeaseDuration` time.

OCPBUGS-18278: Address long acquire times during upgrade

---

install/03_rbac.yaml

Add missing `watch` verb for `clusteroperators` to the `cluster-autoscaler-operator` clusterrole.

OCPBUGS-19411: cluster-autoscaler-operator: clusterrole add clusteroperators watch

---

pkg/operator/status.go

We are seeing sometimes, that the Cluster Autoscaler status never gets reported. Looking at the logic, it's possible here that we wait forever for the informers to sync, but, if they never actually sync, the status won't get reported.
I'm not sure why they wouldn't sync, but, having a timeout seems reasonable to prevent this infinite hang.
If we start seeing this timeout hit repeatedly, then my theory is correct, and we can then investigate why the informers aren't syncing correctly.

OCPBUGS-18954: Ensure status reporter caches exit if they don't sync

---

pkg/controller/clusterautoscaler/clusterautoscaler.go

Depends on https://github.com/openshift/kubernetes-autoscaler/pull/261
When autoscale from zero is enabled in non-amd64 single-arch clusters on cloud providers managed by actuators that do not set the architecture in the capacity annotations (ref. [MIXEDARCH-129](https://issues.redhat.com//browse/MIXEDARCH-129)), passing the argument --scale-up-from-zero-default-arch will allow not to default on the amd64 architecture for building the generic labels to scale out nodegroups from zero.
This commit sets the argument for the cluster-autoscaler to runtime.GOARCH.
/hold

OCPBUGS-18137: Provide the architecture of the control plane as argument to --scale-up-from-zero-default-arch

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

kubernetes/autoscaler#6066 merged using an env var instead of the command line argument, we decided to go with downstream in openshift/kubernetes-autoscaler#261. We will need to be ready for onboarding that change during the next rebase. 
This PR adds the env var to the deployment of the autscaler: we could merge this and prepare another revert PR for 6b7a17780f92775d4e08b9a594b7f1a29a75f7e8 or do both of them at once, during the next rebase. Wdyt @elmiko ?
Refers #284

MIXEDARCH-429: Add the environment variable value for CAPI_SCALE_ZERO_DEFAULT_ARCH

---

install/07_deployment.yaml

All openshift operators must include FallbackToLogsOnError to ease debugging.

OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

---

pkg/controller/clusterautoscaler/clusterautoscaler.go

The rebase of the autoscaler to 1.29 will downstream the changes in kubernetes/autoscaler#6066 and drop the changes in https://github.com/openshift/kubernetes-autoscaler/pull/261, leading to a failure in the deployment of the autoscaler because of the unrecognized command-line argument (if I'm not wrong).
The rebase of the autoscaler should include the commit in https://github.com/elmiko/kubernetes-autoscaler/commit/2120c26a5116f9c3a3ed752bd041d28b3109aa2a to be dropped on the next rebase and after this PR merge.
This PR reverts openshift/cluster-autoscaler-operator#284 and should be merged after the kubernetes-autoscaler repo is rebased to 1.29.

MIXEDARCH-429: Revert "OCPBUGS-18137: Provide the architecture of the control plane as argument to --scale-up-from-zero-default-arch"

---

install/01_clusterautoscaler.crd.yaml
pkg/apis/autoscaling/v1/clusterautoscaler_types.go

This change makes the documentation more accurate by switching from "gigabytes" to "GiB", the old value was incorrect.

OCPBUGS-28207: update min/max memory limit documentation

---

pkg/controller/machineautoscaler/machineautoscaler_controller.go
pkg/controller/machineautoscaler/machinetarget.go
pkg/controller/machineautoscaler/machinetarget_test.go

Hello! This is a PR to update the CAO to add the upstream scale from zero annotations if it's only the old annotations that are there. Thanks!

OCPCLOUD-2493: Update CAO to add upstream annotations

---

pkg/operator/operator.go

This change updates the webhook server to use TLSv1.3.
Other TLS configuration options are possible, by specifying additional options in the function  defined - or defining another function.

OCPBUGS-20565: Set webhook minimum TLS version to 1.3

---

install/07_deployment.yaml

References:
- [SCC docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html)
- [SCC pinning docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth)

AUTH-482: set required-scc for openshift workloads

---

pkg/controller/clusterautoscaler/clusterautoscaler.go

in 1.30 the AWS cloud provider added a new label:
`topology.k8s.aws/zone-id`, this change adds it to the ignore list. For more details about the label, see https://github.com/kubernetes/cloud-provider-aws/issues/300

OCPBUGS-35952: add aws zone-id to ignore labels

---

pkg/controller/clusterautoscaler/clusterautoscaler.go

This change disables the maximum number of nodes that can be soft tainted or untainted at once for deletion.

OCPBUGS-42132: set max soft bulk taint count to zero

---

pkg/controller/clusterautoscaler/clusterautoscaler_controller.go

Fixes: https://issues.redhat.com/browse/OCPBUGS-57041
This bug was happening because the platform type of the cluster was not updated before CreateAutoscaler is being called. This results in some arguments not getting added to the deployment spec initially, but during a subsequent quick reconcile, the platform type is updated in the UpdateAutoscaler function. So immediately, the args are now added to the deployment, which triggers a new pod(s) rollout.

OCPBUGS-57041: update cluster provider type early

---

OWNERS

Removes the subcomponent in the OWNERS file and changes the component to `Cluster Autoscaler` to reflect the current changes in moving the cluster-autoscaler-operator to the Autoscale team.

AUTOSCALE-284: Rename Cluster Autoscaler component in OWNERS file
